### ISSUE TITLE
worker.defaultName default

### ISSUE THREAD

**Issue by jwulf** [zeebe-io/spring-zeebe#100]
Can we make this optional: `zeebe.client.worker.defaultName`

And provide a default for it, if it is not specified?

Like `worker-${uuid}`.

It's kinda clunky to have to add this to the configuration.

**Comment by berndruecker** [comment]
I would not doo anything in the Spring integration specifically - if we want to have this we should adjust the default worker name in the Java client: https://github.com/camunda-cloud/zeebe/blob/develop/clients/java/src/main/java/io/zeebe/client/impl/ZeebeClientBuilderImpl.java#L54.

AFAIK the worker defaultName is not mandatory to configure

**Comment by berndruecker** [comment]
I just realized why you have to really set it. I agree that this is annoying and just fixed it now
