### ISSUE TITLE
Define pollInterval in @ZeebeWorker

### ISSUE THREAD

**Issue by ajeans** [zeebe-io/spring-zeebe#104]
`JobWorkerBuilderStep3` supports setting various options, including `pollInterval`

However `@ZeebeWorker` and the related `ReadZeebeWorkerValue` do not provide support for this option, only name, type, timeout and maxJobsActive.

Is it possible to add this additional option to `ZeebeWorker`?

I can even provide a patch, this should be pretty trivial.

Thanks

**Comment by ajeans** [comment]
OK it seems that the patch already exists as it is ready in pull request https://github.com/zeebe-io/spring-zeebe/pull/97

**Comment by berndruecker** [comment]
I close this know as it seems to be closed by https://github.com/zeebe-io/spring-zeebe/pull/111 - feel free to re-open if I missed something
