### ISSUE TITLE
Ability to decorate workers 

### ISSUE THREAD

**Issue by DominikMostek** [zeebe-io/spring-zeebe#105]
I would like to be able to decorate workers with handlers that can implement cross-cutting concers. 
Examples:

- Logging:     I Would like to be able to extract traceId from a job variables and add it to MDC. Similar to Servlet filters
- Exception handlers:     wrap all workers in custom exception handler. Similar to ControllerAdvice in spring

Possible solution:
ZeebeWorkerPostProcessor could accept list of decorators and apply them in
`handler((jobClient, job) -> m.getBeanInfo().invoke(jobClient, job))`

I would like to create a PR if this feature has the support of the community.

**Comment by jangalinski** [comment]
I like the use case, but I wondered if this could be achieved by regular spring aop? Any thoughts on that?

**Comment by DominikMostek** [comment]
@jangalinski Thats the way I am doing it right now. Good solution but maybe a built-in one would suite more. Or at least mention this in the documentation as the standard way of doing it.

**Comment by berndruecker** [comment]
@DominikMostek Sorry for joining the discussion late. I like using default Spring behavior if possible to avoid the code base growing unnecessarily. But it would be great to provide some example/hints in the readme - happy to accept a PR about this!
