### ISSUE TITLE
Ability override ZeebeObjectMapper 

### ISSUE THREAD

**Issue by jooble** [zeebe-io/spring-zeebe#109]
Hi, I want to override ZeebeObjectMapper or customize it.
I use Kotlin and default objectMapper`s settings don`t support kotlin module.

I use a workaround - deserialize of variables with my objectMapper, but that`s not what I want

**Comment by aivinog1** [comment]
Hi @jooble! I'm not a part of the Zeebe team, but I want to say, that I'm working on the same issue in the Zeebe client: https://github.com/zeebe-io/zeebe/issues/5578. I think that after the aforementioned issue will be done, we can add support for customizing in the Spring client :)

**Comment by aivinog1** [comment]
Hi @jooble! A little update on this one: since 1.0.0-alpha is out I can start working on this issue. But, I don't think that it will be done until `zeebe-client-java` 1.0.0 is out.

**Comment by berndruecker** [comment]
I merged the code into master. @aivinog1 - do you think you could add a small example to the readme to point people on how to customize the object mapper (this example might also give the hint why you want to do such a thing)?

**Comment by aivinog1** [comment]
@berndruecker Sure, I'll do it.
