### ISSUE TITLE
release 0.2.0

### ISSUE THREAD

**Issue by jangalinski** [zeebe-io/spring-zeebe#34]
This will support zeebe 0.7.0

**Comment by jangalinski** [comment]
new dev version: 0.3.0-SNAPSHOT

**Comment by jangalinski** [comment]
@menski did you also release to maven central? I guess it should have shown up by now. Maybe it got stuck?

**Comment by menski** [comment]
@jangalinski sorry I had to pause my release process for a while. I'm currently finishing it up. Just released it on maven central.

**Comment by menski** [comment]
All artifacts should be available
