### ISSUE TITLE
Provide typed topic listeners

### ISSUE THREAD

**Issue by menski** [zeebe-io/spring-zeebe#35]
At the moment it is possible to create a topic listener which registers an [universal event handler](https://github.com/zeebe-io/zeebe/blob/d89ee4918668a080bf68c922f483d900a4f99c24/client-java/src/main/java/io/zeebe/client/event/TopicSubscriptionBuilder.java#L47). It would be nice to be able to create a topic listener which can handle typed events, i.e. [task events](https://github.com/zeebe-io/zeebe/blob/d89ee4918668a080bf68c922f483d900a4f99c24/client-java/src/main/java/io/zeebe/client/event/TopicSubscriptionBuilder.java#L55), [workflow events](https://github.com/zeebe-io/zeebe/blob/d89ee4918668a080bf68c922f483d900a4f99c24/client-java/src/main/java/io/zeebe/client/event/TopicSubscriptionBuilder.java#L71), [workflow instance events](https://github.com/zeebe-io/zeebe/blob/d89ee4918668a080bf68c922f483d900a4f99c24/client-java/src/main/java/io/zeebe/client/event/TopicSubscriptionBuilder.java#L63) and [incident events](https://github.com/zeebe-io/zeebe/blob/d89ee4918668a080bf68c922f483d900a4f99c24/client-java/src/main/java/io/zeebe/client/event/TopicSubscriptionBuilder.java#L79). This could ease to develop monitor applications using spring-zeebe.

**Comment by saig0** [comment]
Topic listeners was removed a while ago.
