### ISSUE TITLE
Adjust to new POJO configuration for Broker

### ISSUE THREAD

**Issue by meyerdan** [zeebe-io/spring-zeebe#36]
In the context of zeebe-io/zeebe#815 we are restructuring and simplifying the configuration.

As a result, there is a top-level POJO cofiguration class named [BrokerCfg](https://github.com/zeebe-io/zeebe/blob/master/broker-core/src/main/java/io/zeebe/broker/system/configuration/BrokerCfg.java)

When bootstrapping the broker, it can either read this from TOML or a pre-existing object can be provided.
See the following [Constructor](https://github.com/zeebe-io/zeebe/blob/master/broker-core/src/main/java/io/zeebe/broker/Broker.java#L59) in Broker.

As far as I can tell, this means that we need to adjust some configuration code in this project.

Also, the broker does  not have the feature anymore to use a temp directory. This can be done more easily in a testing rule outside of the broker by passing in a "basePath" pointing to a temp directory to the constructor mentioned above.

**Comment by jangalinski** [comment]
This is great news!

**Comment by jangalinski** [comment]
I need an ActorClock to create a broker. Can you tell me how to obtain it?

**Comment by meyerdan** [comment]
Just pass in null

**Comment by jangalinski** [comment]
I see
I like API that speaks for itself :-) might be a good idea to introduce @Nullable or Optional for this kind of stuff ...

**Comment by meyerdan** [comment]
Just add a constructor that does not require the parameter

**Comment by jangalinski** [comment]
how would the broker react on actorClok==null? I see that the client switches to a default implementation, but I don't see that in the broker.
Also: the broker has a lot of constructors already (via Stream, via cfg, ...) duplicating each of them to have actorClock optional doesn't seem right.  Maybe just hava the new Broker(systemContext) constructor and move the rest to a broker Builder (as done in the client)?

**Comment by meyerdan** [comment]
> how would the broker react on actorClock==null? I see that the client switches to a default implementation, but I don't see that in the broker.

It is [here](https://github.com/zeebe-io/zb-util/blob/master/util/src/main/java/io/zeebe/util/sched/ActorThread.java#L103), you cannot find that :)

> Also: the broker has a lot of constructors already (via Stream, via cfg, ...) duplicating each of them to have actorClock optional doesn't seem right. Maybe just hava the new Broker(systemContext) constructor and move the rest to a broker Builder (as done in the client)?

That makes sense, to us it is not high prio since starting the broker explicitly via Java code is not super common so it is not something we optimize for right now. But a builder definately makes sense. I am happy to merge a PR on that :dagger:

**Comment by salaboy** [comment]
@meyerdan @jangalinski can we close this one?

**Comment by saig0** [comment]
The spring-starter for the broker was removed a while ago.
