### ISSUE TITLE
support zeebe 0.11.0

### ISSUE THREAD

**Issue by jangalinski** [zeebe-io/spring-zeebe#37]
especially the new client POJO config

see also #36

**Comment by jangalinski** [comment]
update version, use new fluent API

**Comment by saig0** [comment]
@jangalinski , when do you want to release the new version 0.3.0?

**Comment by berndruecker** [comment]
Still a todo: Rename annotation, like @ZeebeTaskListener to @ZeebeWorker (or @ZeebeJobListener?)

**Comment by jangalinski** [comment]
I choose ZeebeWorker. Whats a good name for the TopicListener?

**Comment by berndruecker** [comment]
Good choice. I actually wouldn't put much thought in the TopicListener as this might go away in this form in the next release (if you need details happy to jump on a call)
