### ISSUE TITLE
Kotlin API prevents Maven central release

### ISSUE THREAD

**Issue by menski** [zeebe-io/spring-zeebe#47]
The release fails because there is a zeebe api module written in Kotlin, which does not generate a javadoc jar. Therefore maven central rejects the upload of the release.

```
16:28:15     [ERROR] Nexus Staging Rules Failure Report
16:28:15     [ERROR] ==================================
16:28:15     [ERROR] 
16:28:15     [ERROR] Repository "iozeebe-1173" failures
16:28:15     [ERROR]   Rule "javadoc-staging" failures
16:28:15     [ERROR]     * Missing: no javadoc jar found in folder '/io/zeebe/spring/spring-zeebe-api/0.3.0'
```

**Comment by menski** [comment]
@jangalinski any ideas how we want to handle this? I never worked with Kotlin before so not really sure if it is even possible to get the javadoc jar

**Comment by Zelldon** [comment]
I think you need to use dokka 

https://github.com/Kotlin/dokka/blob/master/README.md#using-the-maven-plugin

Found the hint here:
https://kotlinlang.org/docs/reference/using-maven.html

**Comment by menski** [comment]
@jangalinski I would remove the Kotlin API from this project. The reasons are that it is incomplete and not maintained, i.e. [Exceptions.kt](https://github.com/zeebe-io/spring-zeebe/blob/master/client/api/src/main/kotlin/Exceptions.kt), and as far as I understand it is not related to Spring. I propose to create another community project which could contain a complete Kotlin Client for Zeebe. This would also allows us to fix this issue and release the new version.

**Comment by jangalinski** [comment]
Go ahead
