### ISSUE TITLE
Version of spring zeebe

### ISSUE THREAD

**Issue by kratosmat** [zeebe-io/spring-zeebe#50]
Hi all,
Do you foresee to maintain and upgrade spring-zeebe project, I have noticed that the last version us zeebe-client 0.15.0 instead of 0.17.0, the last version of broker.

Thanks a lot,
Matteo.

**Comment by menski** [comment]
Hi @kratosmat,

there is a pending PR for the upgrade to Zeebe 0.17 (#55). And yes we intend to maintain spring-zeebe in the future.

Cheers,
Sebastian
