### ISSUE TITLE
How to export data to elastic search  from spring zeebe broker by exporter

### ISSUE THREAD

**Issue by regojoyson** [zeebe-io/spring-zeebe#54]
I want to export my data to elastic search using exporter from spring Zeebe. so is there any way?

**Comment by salaboy** [comment]
@regojoyson that is already working.. and it is usually the default way. There is the elastic exporter already in the official brokers. Is that not working for you?

**Comment by regojoyson** [comment]
@salaboy  Thanks, I got it.
