### ISSUE TITLE
Job Worker exceptions are not propagated

### ISSUE THREAD

**Issue by menski** [zeebe-io/spring-zeebe#56]
Job workers fail to report exceptions as failed jobs as we do not handle `InvocationTargetExpcetions` in https://github.com/zeebe-io/spring-zeebe/blob/a00daa9e62bccfc796419b0ed59401afd345ee63/client/spring-zeebe/src/main/java/io/zeebe/spring/client/bean/MethodInfo.java#L31

The returned exception will have `null` as exception message which again triggers an exception in the protobuf serializer of the Zeebe client as it is not a valid string value. Also the user does expect the target exception as failed job exception message and not the wrapper.

Reference: https://forum.zeebe.io/t/incident-was-not-created-even-same-service-task-failing-multiple-times/414

**Comment by regojoyson** [comment]
Is this issue fixed or still open?

**Comment by menski** [comment]
@regojoyson it is still open. There is a open PR waiting for review (#57) and then we have to release a new version of spring-zeebe.
