### ISSUE TITLE
print nice stacktrace when client can't connect to broker on start

### ISSUE THREAD

**Issue by jangalinski** [zeebe-io/spring-zeebe#6]
ran a spring-zeebe client without active broker: nasty recursive stacktrace full of NPE and connection refused ....

It should just state that the configured broker is not reachable ... and suggest checking the config or the state.

**Comment by meyerdan** [comment]
Should probably be implemented in the java client itself, no?

**Comment by jangalinski** [comment]
yes, you are right ... can we move an issue?

**Comment by menski** [comment]
I create an issue in Zeebe for that https://github.com/zeebe-io/zeebe/issues/661, Feel free to add more feedback.
