### ISSUE TITLE
Part of the configuration file does not work

### ISSUE THREAD

**Issue by HuangXiaoyu3331** [zeebe-io/spring-zeebe#66]
I configured "zeebe.client.worker.threads=3"  in application.properties, but I found that it didn't work, numJobWorkerExecutionThreads still 1
``` java
public class ZeebeClientBuilderImpl implements ZeebeClientBuilder, ZeebeClientConfiguration {

  private String brokerContactPoint = "0.0.0.0:26500";
  private int jobWorkerMaxJobsActive = 32;
  private int numJobWorkerExecutionThreads = 1;
  private String defaultJobWorkerName = "default";
  private Duration defaultJobTimeout = Duration.ofMinutes(5);
  private Duration defaultJobPollInterval = Duration.ofMillis(100);
  private Duration defaultMessageTimeToLive = Duration.ofHours(1);
  private Duration defaultRequestTimeout = Duration.ofSeconds(20);
````

It seems the problem is that the ZeebeClientStarterAutoConfiguration.class is missing the following code 
``` java
builder.numJobWorkerExecutionThreads(configurationProperties.getNumJobWorkerExecutionThreads)
```

This is the ZeebeClientStarterAutoConfiguration.class current code 
``` java
@EnableConfigurationProperties(ZeebeClientConfigurationProperties.class)
@Configuration
@RequiredArgsConstructor
public class ZeebeClientStarterAutoConfiguration {

  private final ZeebeClientConfigurationProperties configurationProperties;
  
  @Bean
  @Primary
  public ZeebeClientBuilder builder() {
    final ZeebeClientBuilderImpl builder = new ZeebeClientBuilderImpl();

    builder.brokerContactPoint(configurationProperties.getBrokerContactPoint());
    builder.defaultJobPollInterval(configurationProperties.getDefaultJobPollInterval());
    builder.defaultJobTimeout(configurationProperties.getDefaultJobTimeout());
    builder.defaultJobWorkerMaxJobsActive(configurationProperties.getDefaultJobWorkerMaxJobsActive());
    builder.defaultJobWorkerName(configurationProperties.getDefaultJobWorkerName());
    builder.defaultMessageTimeToLive(configurationProperties.getDefaultMessageTimeToLive());
    
    return builder;
  }
}
```

**Comment by spulci** [comment]
It seems you're right. Do you thik to have a PR for this? Otherwise I can try to have one for this in the next few days :)

**Comment by salaboy** [comment]
@spulci let's try to get this in as well.

**Comment by HuangXiaoyu3331** [comment]
> It seems you're right. Do you think to have a PR for this? Otherwise I can try to have one for this in the next few days :)

OK, I have submitted a pull request

**Comment by eclipdata-gvillacis** [comment]
@salaboy @spulci When are they going to approve the commit that @HuangXiaoyu3331 did and add it to the master branch? I am just needing to solve a performance problem in a worker that I am building through a spring boot microservice using more threads.

**Comment by spulci** [comment]
> @salaboy @spulci When are they going to approve the commit that @HuangXiaoyu3331 did and add it to the master branch? I am just needing to solve a performance problem in a worker that I am building through a spring boot microservice using more threads.

A rebase has been requested to the commiter, done a few hours ago. I'm quite sure that a merge will be done shortly after so that the master branch will be ready for a new release ;)
