### ISSUE TITLE
when deploy version  0.7.0 ? 

### ISSUE THREAD

**Issue by Jungle666** [zeebe-io/spring-zeebe#70]
0.6.0 can't support zeebe 0.21.1，I am waitting for  version 0.7.0 .

**Comment by salaboy** [comment]
@Jungle666 it was released yesterday to maven central.. it hasn't been announced yet. 
But you can already try it out. 

https://search.maven.org/artifact/io.zeebe.spring/spring-zeebe-starter/0.7.0/jar

**Comment by Jungle666** [comment]
It' OK now, Thank you.

**Comment by Jungle666** [comment]
> @Jungle666 it was released yesterday to maven central.. it hasn't been announced yet.
> But you can already try it out.
> 
> https://search.maven.org/artifact/io.zeebe.spring/spring-zeebe-starter/0.7.0/jar

It does not support java8.  how should I solve it？

[ERROR] class file has the wrong version 55.0, should be 52.0
[ERROR] Please delete the file or make sure it is in the correct classpath subdirectory.
