### ISSUE TITLE
version 0.7.0 does not support java8. how should I solve it？

### ISSUE THREAD

**Issue by Jungle666** [zeebe-io/spring-zeebe#71]
i can't compile project because：

[ERROR] class file has the wrong version 55.0, should be 52.0
[ERROR] Please delete the file or make sure it is in the correct classpath subdirectory.

**Comment by salaboy** [comment]
Yes unfortunately there are not soo many solutions. For 0.8.0 we will provide backward compatibility if possible. You can compile the project with JDK 8 and then use your artefacts in the mean time..

**Comment by Jungle666** [comment]
Thanks for your response.  Our prod enveriment is jre 8, It's hard to switch to JDK 11. Could you offer me a snapshot version with java 8? I am in an emergency.

**Comment by Jungle666** [comment]
@salaboy Thanks for your response. Our prod enveriment is jre 8, It's hard to switch to JDK 11. Could you offer me a snapshot version with java 8? I am in an emergency.

**Comment by salaboy** [comment]
@Jungle666 you can create your own snapshots right? what would be the difference between our providing us those snapshots and you creating them by building the projects?>

**Comment by Jungle666** [comment]
@salaboy I was trying to build snapshots，but failed. I dont know what's going on. It seems like maven error.  could you help me solve it?

error info is :
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (java-compile) on project spring-zeebe-util: Fatal error compiling: Invalid tag: --release -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :spring-zeebe-util

**Comment by Zelldon** [comment]
To build it with jdk 8 you have to set the source and target like this:

```
  <build>
    <defaultGoal>clean install</defaultGoal>
    <pluginManagement>
      <plugins>
        <!-- Disable adding license header -->
        <plugin>
          <groupId>com.mycila</groupId>
          <artifactId>license-maven-plugin</artifactId>
          <configuration>
            <skip>true</skip>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.0</version>
          <configuration>
          <source>1.8</source>
          <target>1.8</target>
          </configuration>
        </plugin>
        <plugin>
          <artifactId>kotlin-maven-plugin</artifactId>
          <groupId>org.jetbrains.kotlin</groupId>
          <version>${kotlin.version}</version>
        </plugin>
      </plugins>
    </pluginManagement>
```

Instead of using the release configuration

```
  <build>
    <defaultGoal>clean install</defaultGoal>
    <pluginManagement>
      <plugins>
        <!-- Disable adding license header -->
        <plugin>
          <groupId>com.mycila</groupId>
          <artifactId>license-maven-plugin</artifactId>
          <configuration>
            <skip>true</skip>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.0</version>
          <configuration>
            <release>${java.version}</release>
          </configuration>
        </plugin>
        <plugin>
          <artifactId>kotlin-maven-plugin</artifactId>
          <groupId>org.jetbrains.kotlin</groupId>
          <version>${kotlin.version}</version>
        </plugin>
      </plugins>
    </pluginManagement>
```

More details here https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html

**Comment by Jungle666** [comment]
@salaboy    zeebe-broker has same problem as spring-zeebe， Zeebe-broker 0.21.1 was build with java 11 , is that mean I should do the same thing to Zeebe-broker ?

**Comment by Jungle666** [comment]
@salaboy same problem.
 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (java-compile) on project spring-zeebe-broker: Compilation failure
[ERROR] /E:/obs/zeebe/spring-zeebe-master/broker/spring-zeebe-broker/src/main/java/io/zeebe/spring/broker/ZeebeBrokerObjectFactory.java:[3,23] cannot access io.zeebe.broker.Broker
[ERROR] error class file: \.m2\repository\io\zeebe\zeebe-broker\0.21.1\zeebe-broker-0.21.1.jar(io/zeebe/broker/Broker.class)
[ERROR] class file has the wrong version 55.0, should be 52.0
[ERROR] Please delete the file or make sure it is in the correct classpath subdirectory.

**Comment by salaboy** [comment]
Unfortunately not, Zeebe core strongly depend on jdk11 meaning that only client modules will provide backward compatibility to jdk8 . If you want to create the other artifacts you can comment the Zeebe broker spring integration

**Comment by Jungle666** [comment]
@salaboy OK，got it. Thanks.

**Comment by Jungle666** [comment]
@salaboy I got the answer from zeebe-broker, It is expected since the broker only supports java 11+.
Is there no way to support java 8? 
https://github.com/zeebe-io/zeebe/issues/3369

**Comment by Jungle666** [comment]
@salaboy I'm  using java 11,but failed agin,

2019-11-15 09:40:18|main|AnnotationConfigServletWebServerApplicationContext|Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'subscriptionBuilderPostProcessor' defined in io.zeebe.spring.client.config.processor.PostProcessorConfiguration: Unsatisfied dependency expressed through method 'subscriptionBuilderPostProcessor' parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'io.zeebe.spring.client.config.ZeebeClientSpringConfiguration': Unsatisfied dependency expressed through field 'zeebeClientBuilder'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'io.zeebe.client.ZeebeClientBuilder' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
2019-11-15 09:40:18|main|ConditionEvaluationReportLoggingListener|

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-11-15 09:40:18|main|LoggingFailureAnalysisReporter|

***************************
APPLICATION FAILED TO START
***************************

Description:

Field zeebeClientBuilder in io.zeebe.spring.client.config.ZeebeClientSpringConfiguration required a bean of type 'io.zeebe.client.ZeebeClientBuilder' that could not be found.


Action:

Consider defining a bean of type 'io.zeebe.client.ZeebeClientBuilder' in your configuration.

**Comment by salaboy** [comment]
@Jungle666 sorry for the lack of responses here.. I was traveling ..

What kind of configuration did you tried to get that error? I am running with JDK 11 without any problem.. and just to answer your question.. for Zeebe Core there is no support for JDK 8 .. we can only provide support for JDK 8 in client libraries..

**Comment by imsuperman0920** [comment]
@Jungle666 
Do you compile with jdk 8 successfully ?

**Comment by berndruecker** [comment]
I just switched Java version back to 8 for Spring Zeebe. As we removed the broker part that should cause no problems

**Comment by Jungle666** [comment]
> @Jungle666
> Do you compile with jdk 8 successfully ?

Use jdk11 finnally.
