### ISSUE TITLE
Remove Zeebe Client logo from Spring Boot Startup

### ISSUE THREAD

**Issue by berndruecker** [zeebe-io/spring-zeebe#77]
Currently there is an own logo coming with the ZeebeClient - I consider this bad practice in the Spring Boot ecosystem, as Zeebe might be one starter amongst others. I would vote to remove it.

```

 ███████╗███████╗███████╗██████╗ ███████╗     ██████╗██╗     ██╗███████╗███╗   ██╗████████╗
 ╚══███╔╝██╔════╝██╔════╝██╔══██╗██╔════╝    ██╔════╝██║     ██║██╔════╝████╗  ██║╚══██╔══╝
   ███╔╝ █████╗  █████╗  ██████╔╝█████╗      ██║     ██║     ██║█████╗  ██╔██╗ ██║   ██║
  ███╔╝  ██╔══╝  ██╔══╝  ██╔══██╗██╔══╝      ██║     ██║     ██║██╔══╝  ██║╚██╗██║   ██║
 ███████╗███████╗███████╗██████╔╝███████╗    ╚██████╗███████╗██║███████╗██║ ╚████║   ██║
 ╚══════╝╚══════╝╚══════╝╚═════╝ ╚══════╝     ╚═════╝╚══════╝╚═╝╚══════╝╚═╝  ╚═══╝   ╚═╝

  Spring-Boot:  (v2.2.1.RELEASE)
  Spring-Zeebe: (v0.7.0)
  Zeebe-Client: (v0.21.1)
```

Any objections or opinions?

**Comment by jangalinski** [comment]
The `banner.txt` coming from a library will be overwritten by a banner your spring application provides itself ... so this is just an issue if you do not use a banner. So I see no harm in having one.

**Comment by salaboy** [comment]
I don't see an issue either.. as a library I would prefer not to add a banner .. but unless we have someone complaining about it.. I wouldn't bother right now..

**Comment by berndruecker** [comment]
I personally find it too aggressive given we just add a client library. Think of adding a JDBC library and then you get a Oracle Banner in your face. Would you like this?
So if nobody pushs back harder I would still move on and remove it.

**Comment by salaboy** [comment]
@berndruecker I totally agree.. is there a way to override it programatically @jangalinski  ?

**Comment by salaboy** [comment]
@berndruecker maybe.. we should remove the original banner.txt from Zeebe Core.. that sounds like the right decision.. and only add the banner.txt file if you are creating a spring boot application that is a broker for example.

**Comment by berndruecker** [comment]
> f you are creating a spring boot application that is a broker for example.

Which is not a use case we support as far as I know - probably we should even remove this part completely? I can create a separate issue for that.

**Comment by jangalinski** [comment]
What do you think of the banner in the camunda starter? What do you think of the default banner provided by spring boot? 
I don‘t really get the point ...

If you want your own banner, create one, if you do not want any banner, doable it in application.yaml ...

**Comment by jangalinski** [comment]
I like the banner, but just go ahead and remove it then.

**Comment by berndruecker** [comment]
Happy that you understand it Jan :-)
Nut - but seriously - feel free to approach me. I definitely want to avoid hard feelings with the man investing his free time into starting great things in our community!

But overall I think it just a bad practice that libraries have their own banner. Show me other client libraries that do this. It typically leads to a bit of confusion on the users side as well. And honestly: Nobody really adds banner.txt to their client apps - at least not as far as I have seen. Probably except Josh Long ;-) Happy to discuss!

The same problem applies basically to the Camunda BPM banner as well - but as the starter really starts the whole engine it is a bit less of a problem there.

**Comment by berndruecker** [comment]
@salaboy Just removed it from the client for now - we should discuss the broker separately: https://github.com/zeebe-io/spring-zeebe/issues/78

**Comment by jangalinski** [comment]
> Happy that you understand it Jan :-)

No hard feelings on my side ... I didn't get why this was an issue in the first place ... but you somehow got me with the "client-lib" point ... so now it's gone, I do not feel any need to continue discussing ... 
Having a rough day and you just got "proxy-punched" :-), sorry for that.
