### ISSUE TITLE
Reevaluate if starting the broker via Spring Boot is a valid supported use case of the Spring Boot Starter

### ISSUE THREAD

**Issue by berndruecker** [zeebe-io/spring-zeebe#78]
Currently you can also start the core broker via Spring Boot Starter.

My personal feeling is that this is not what we want people to do - and thus also don't support. I will ping a couple of people for their opinion and collect the results here.

So if you have a strong argument pro/contra please add!

**Comment by menski** [comment]
We support the Zeebe broker official in a docker/k8s environment. Running it as a spring boot starter is not tested or covered by the official support, and not recommend from our side. I would vote for removing the broker part of this project.

**Comment by jangalinski** [comment]
I find it really useful during testing/dev as I can just configure a TestApplication that acts as both, broker and client ...  I mean, it's just wrapping the ZeebeBroker-instance in a smart lifecycle ... no harm done here.

I would vote for the opposite direction: the spring boot universe provides a lot of best practices and de facto standards for running and configuring java enterprise server applications ... why not switch the zeebe broker to spring boot completely? I mean, it is not supposed to be embeddable, but it would benefit from transparent yaml/environment properties, clean lifecycle, and hooks for service registry, security, monitoring, ... why keeping the broker lib on Java SE/toml?

**Comment by berndruecker** [comment]
Hi Jan. We actually have a different view on this. 

We know that we still need to define a proper testing story (see https://github.com/zeebe-io/zeebe/issues/3419). But we do not want to center this around Spring Boot but rather think about it more holistically. Of course this should also result in a defined way of how to run tests in Spring Boot. And I hope we even end up with a really simple starter we can probably use - but it is yet to be defined.

That's said we want to keep the broker small, isolated and under control. So we decided against using Spring or Spring Boot within the core, meaning of course that we have to reimplement some things. You can always challenge that decision, but as it is already settled I think we better save that energy ;-) Just one example: Keep in mind that we have to support this piece of software in critical high-load scenarios. If the broker runs as Sping Boot component, we really have to understand the whole setup and probably even Spring Boot versions and what not. Users can easily break things by adding own starters that might interfere with whatever component. We want to completely avoid that situation by controlling the exact environment we are running in. As in the long run the support effort is much higher with such a product than the initial development effort. Hope hat makes sense for you! If not I am happy to discuss - but probably prefer F2F then - WDYT?

**Comment by jangalinski** [comment]
Yes of course ... F2F is a good idea ... I was just trying  to place a twist in this story ... knowing that it would not "just" happen.
