### ISSUE TITLE
Add HealthIndicator to add basic ZeebeConnection info available via Actuator

### ISSUE THREAD

**Issue by berndruecker** [zeebe-io/spring-zeebe#79]
Add a Spring Boot Actuator (https://www.baeldung.com/spring-boot-actuators) Helth indicator to the Zeebe client, that will switch to unhealthy if the client connection is not successful.

A TypeScript example using the NodeJS client library did this by using GRPC hooks (https://github.com/camunda-cloud/zeebe-http-worker/blob/master/src/worker/worker.ts#L86) - probably possible in Java as well?

**Comment by salaboy** [comment]
@berndruecker we provide here starters for spring boot.. that means that is your application responsibility to add the actuators to your actual service.. that is normal practice as far as I know.

**Comment by salaboy** [comment]
@berndruecker for example in your case the `zeebe-http-worker` is the one responsible for adding that.

**Comment by salaboy** [comment]
I think that now I understand what you mean.. so you want to provide an extended endpoint in the actuators for the Zeebe Brokers .. and that makes a lot more sense to me.

**Comment by berndruecker** [comment]
Yes, indeed. It should report some information about the Zeebe Connection status. I updated the title to reflect this.
But not urgent at the moment to be honest.
