### ISSUE TITLE
Allow job worker type to be configurable via environment

### ISSUE THREAD

**Issue by berndruecker** [zeebe-io/spring-zeebe#83]
this will fix https://github.com/zeebe-io/zeebe-http-worker/issues/35

**Comment by berndruecker** [comment]
In order to support this I know added one additional config parameter:

`
zeebe.client.worker.defaultType="xyz"
`

to be consistent I also renamed the worker name to
`
zeebe.client.worker.defaultNyme="xyz"
`

**Comment by saig0** [comment]
This is implemented with version 0.22.0 :rocket:
