### ISSUE TITLE
Upgrade to Zeebe 0.23.0

### ISSUE THREAD

**Issue by Firestorm87** [zeebe-io/spring-zeebe#92]
There is a new 0.23 java-client, but not an spring-pendant.

**Comment by berndruecker** [comment]
Adjusted with https://github.com/zeebe-io/spring-zeebe/commit/03df6bd02250ead386b75762fa72de0b9b0a11e2 - will do a release soon

**Comment by berndruecker** [comment]
Currently waiting for https://github.com/zeebe-io/spring-zeebe/issues/81 and https://github.com/zeebe-io/zeebe/issues/4356 before doing a release

**Comment by berndruecker** [comment]
Seems zeebe-io/zeebe#4356 is not related to this at all. Merged #81 and will go ahead and release

**Comment by berndruecker** [comment]
Just released 0.23.0
