### ISSUE TITLE
Does it support Java 8?

### ISSUE THREAD

**Issue by saikrishna-chunchu** [zeebe-io/spring-zeebe#95]
I am seeing below error when I am trying to run the application that is using this library in jre 8. What is the officially supported java version for this library (>=java 8 or >= java 11)?

java.lang.UnsupportedClassVersionError: io/zeebe/spring/client/EnableZeebeClient has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by Jungle666** [comment]
java 8 not support for 0.7.0 and 0.7.1，It is ok for new version 0.23.0

**Comment by berndruecker** [comment]
The Zeebe client and Spring Boot integration supports Java >= Java 8. Please report any issues if you have some
