### ISSUE TITLE
Worker introduces delays to workflow

### ISSUE THREAD

**Issue by jwulf** [zeebe-io/spring-zeebe#98]
Start workflow: 2020-06-28T23:14:37.468Z
get-time worker: 2020-06-28T23:14:50.909Z
make-greeting worker: 2020-06-28T23:14:55.732Z
Finish workflow: 2020-06-28T23:14:56.855Z

This is against a 0.23.3 cluster on Camunda Cloud. It takes 13 seconds from creating a workflow instance for the first worker to retrieve the job. The next worker takes seconds to get the next task.

In this next run, there is a 10-second delay between the first and second task. This is not a server-side issue - the same process run with the Node client runs through in sub-second speed.

Start workflow: 2020-06-28T23:26:43.990Z
get-time worker start: 2020-06-28T23:26:45.169Z
get-time worker finish: 2020-06-28T23:26:46.765Z
make-greeting worker start: 2020-06-28T23:26:57.514Z
make-greeting worker finish: 2020-06-28T23:26:57.974Z
Finish workflow: 2020-06-28T23:26:58.467Z

**Comment by jwulf** [comment]
Here is the reproducer: https://github.com/jwulf/cc-gsg-java/tree/issue-98

You need to put a Camunda Cloud Cluster client credentials in `src/main/resources/application.properties`.

**Comment by salaboy** [comment]
@jwulf something similar was reported to CSharp.. we need to investigate because it might be something related to 0.23.3 more than the clients..

**Comment by salaboy** [comment]
https://forum.zeebe.io/t/slowliness-on-kubernetes-cluster/1382/4

**Comment by Zelldon** [comment]
Might be related to https://github.com/zeebe-io/zeebe/issues/4396

**Comment by salaboy** [comment]
@Zelldon sounds related yes..

**Comment by berndruecker** [comment]
I close this issue as there were a lot of changes up to 1.0.0-alpha5 and we should open new issues if the problem still exists
