### ISSUE TITLE
Project Reactor Support

### ISSUE THREAD

**Issue by jsa4000** [zeebe-io/spring-zeebe#99]
Hi,
I have just a question. 

I would really like to know if Zeebe supports Flux and Mono operators provided by Project reactor.
I am developing a reactive application using webflux and reactive mongodb.

Thanks in advance.
Regards,
Javier

**Comment by salaboy** [comment]
@jsa4000 that sounds like a great idea to me, in Zeebe all mechanisms are PubSub to consume jobs and to interact with the brokers, so creating a Flux integration shouldn't be that difficult, as far as I am aware the current client is not created with Flux, but it will be a great contribution. If you hack something around that I will be happy to help and then we can make it official.

**Comment by Nazeer2013** [comment]
@jsa4000 and @salaboy Any follow-up to this. I'm looking for Zeebe reactive support.  Please inform.

**Comment by salaboy** [comment]
@Nazeer2013 as I mention before, this will be a great community contribution, so far I haven't had time to work on this, but I will happily collaborate with someone.. If you want to take the lead on starting with the project I can help there.

**Comment by aivinog1** [comment]
@salaboy Hi! I'm a newbie in the Project Reactor (and Spring Zeebe as well 😅) but I think I can start working on this. First of all, I think that this issue could be decomposed. First question: what part of the functionality we could extract in the issue that I could start first. Maybe in the first iteration, we could implement a couple of client methods that are most frequently used? In your option what these methods are? Second question: maybe you have a good, solid example, how it should look (other projects, docs, etc.)?

**Comment by aivinog1** [comment]
@salaboy I've created a small prototype of how I think could look like the Reactor client (I've implemented only a topology command). See it here: https://github.com/aivinog1/spring-zeebe/commit/2915b57db23c16d4b438d3e614d102b24500f643. What do you think? :)

**Comment by Nazeer2013** [comment]
@salaboy I can help lead this please inform me of next steps.

**Comment by salaboy** [comment]
@aivinog1 great initiative with kickstarting things.. let's make sure that we don't replace any of the existing stuff.. this will require a new example project for sure. 
@Nazeer2013 @aivinog1 as guidelines, we can use the following project to define which functionalities should come first: https://github.com/salaboy/zeebe-worker-spring-boot-example

As you can see, this only needs the `@ZeebeWorker` annotation to work: https://github.com/salaboy/zeebe-worker-spring-boot-example/blob/master/src/main/java/com/example/demo/DemoApplication.java#L22

But I am guessing that we will need to go one level deep, into the Zeebe Java Client to make it reactive: https://github.com/zeebe-io/zeebe/blob/develop/clients/java/src/main/java/io/zeebe/client/ZeebeClient.java

I am also guessing that as soon as we get the java client reactive, then the spring boot reactive stack should be trivial.

**Comment by aivinog1** [comment]
Hi, @Nazeer2013! :) Feel free to start and lead this task. But if you will need help to solve some task feel free to tag me :)

**Comment by aivinog1** [comment]
@salaboy Thanks :)

**Comment by berndruecker** [comment]
Closing and quoting @npepinpe "this sounds like a nice project, but not something we would want to maintain in the near future - as you can imagine from our back log, we're already quite busy"
